# Generated by Django 5.1.5 on 2025-02-02 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_area_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='alhpax',
            new_name='alphax',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='alhpay',
            new_name='alphay',
        ),
        migrations.AddField(
            model_name='workingtime',
            name='end',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingtime',
            name='start',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
