# Generated by Django 5.1.5 on 2025-03-09 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role_task_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1000)),
                ('output_number', models.CharField(max_length=1000)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=1000)),
                ('sender', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('given', 'Berilgan'), ('process', "Ko'rib chiqilmoqda"), ('failed', 'Rad etilgan'), ('accepted', 'Qabul qilingan'), ('late', 'Kech qolgan')], max_length=100)),
                ('entered', models.DateTimeField(blank=True, null=True)),
                ('exited', models.DateTimeField(blank=True, null=True)),
                ('executed', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='submit',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.application'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
