# Generated by Django 5.1.5 on 2025-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_application_alter_submit_task_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='task',
            new_name='application',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('given', 'Berilgan'), ('process', "Ko'rib chiqilmoqda"), ('failed', 'Rad etilgan'), ('accepted', 'Qabul qilingan'), ('late', 'Kech qolgan')], default='given', max_length=100),
        ),
    ]
