# Generated by Django 5.1.5 on 2025-03-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_task_submit_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='entered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='exited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
