# Generated by Django 5.1.5 on 2025-02-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='control',
            name='longitude',
        ),
    ]
