# Generated by Django 5.1.5 on 2025-02-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_control_latitude_remove_control_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='alphax',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='alphay',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='betax',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='betay',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='deltax',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='deltay',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='gammax',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='gammay',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='end',
            field=models.TimeField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start',
            field=models.TimeField(max_length=1000),
        ),
    ]
