# Generated by Django 5.1.5 on 2025-02-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_area_alphax_alter_area_alphay_alter_area_betax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='image',
        ),
        migrations.AddField(
            model_name='control',
            name='input_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/controls/input'),
        ),
        migrations.AddField(
            model_name='control',
            name='output_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/controls/output'),
        ),
        migrations.AlterField(
            model_name='control',
            name='input_status',
            field=models.CharField(blank=True, choices=[('created', 'Yaratilgan'), ('arrived', 'Kelgan'), ('late', 'Kech qolgan'), ('crash', 'Xatolik'), ('failed', 'Muvaffaqiyatsiz')], default='created', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='output_status',
            field=models.CharField(blank=True, choices=[('created', 'Yaratilgan'), ('gone', 'Ketgan'), ('crash', 'Xatolik'), ('failed', 'Muvaffaqiyatisz')], default='created', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
