# Generated by Django 5.1.5 on 2025-02-13 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Tashkiloti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Tashkiloti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingtime',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Tashkiloti'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='control',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manzili'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan kuni"),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyati'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Davlati'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department', verbose_name="Bo'limi"),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=100, null=True, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Sharifi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization', verbose_name='Tashkiloti'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Lavozimo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Xodim'), ('head', 'Boshliq')], max_length=20, verbose_name='Roli'),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tumani'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Foydalanuvchi nomi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='working_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.workingtime', verbose_name='Ish vaqti'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='end',
            field=models.TimeField(max_length=1000, verbose_name='Ish tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start',
            field=models.TimeField(max_length=1000, verbose_name='Ish boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti'),
        ),
    ]
