# Generated by Django 5.1.5 on 2025-02-13 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_area_org_holiday_org_workingtime_org_alter_area_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Tashkiloti'),
            preserve_default=False,
        ),
    ]
