# Generated by Django 5.1.5 on 2025-02-16 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_branch_alter_user_uuid_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization', verbose_name='Tashkiloti'),
        ),
        migrations.AlterField(
            model_name='department',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization', verbose_name='Tashkiloti'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization', verbose_name='Tashkiloti'),
        ),
    ]
