# Generated by Django 5.1.5 on 2025-02-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_area_org_alter_department_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='input_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='output_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
