# Generated by Django 5.1.5 on 2025-02-17 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_control_input_time_control_output_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_a', models.TextField()),
                ('answer_b', models.TextField()),
                ('answer_c', models.TextField()),
                ('answer_d', models.TextField()),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10)),
                ('score', models.IntegerField(default=2)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.set')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('questions_count', models.IntegerField(default=30)),
                ('passing_score', models.IntegerField(default=50)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Boshlanmagan'), ('started', 'Boshlangan'), ('ended', 'Tugagan'), ('passed', "O'tgan"), ('failed', 'Yiqilgan')], default='created', max_length=100)),
                ('questions', models.ManyToManyField(blank=True, related_name='test_questions', to='users.question')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
