# Generated by Django 5.1.5 on 2025-02-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_set_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
